sudo: required
services:
  - docker

before_install:
  - docker build -t stanlee94/react-client -f ./client/Dockerfile.dev ./client

# Exit with non-zero code will fail your test
script:
  - docker run -e CI=true stanlee94/react-client npm run test

after_success:
  - docker build -t stanlee94/client ./client
  - docker build -t stanlee94/nginx ./nginx
  - docker build -t stanlee94/server ./server
  - docker build -t stanlee94/worker ./worker
  # Push all images to Docker Hub
  # Log in Docker CLI
  - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push stanlee94/client
  - docker push stanlee94/nginx
  - docker push stanlee94/server
  - docker push stanlee94/worker

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-1
  app: multi-container-docker
  env: MultiContainerDocker-env
  bucket_name: elasticbeanstalk-ap-southeast-1-214095551659
  bucket_path: multi-container-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
